### ISSUE TITLE
Unique projects

### ISSUE THREAD

**Issue by locks** [EmberTown/ember-hearth#102]
Should we prevent duplicate projects? "Project already added"?

**Comment by kimroen** [comment]
Yes we should.

**Comment by thomassnielsen** [comment]
The Swift version got a rudimentary check implemented. It compares the path to already added projects. 
https://github.com/EmberTown/ember-hearth/blob/c1bdf1f756cad9718669136b04b9706767ee01ea/Ember%20Hearth/ProjectController.swift#L102-L111

**Comment by locks** [comment]
Fixed in https://github.com/EmberTown/ember-hearth/commit/cc6f124dcf1db350f8d71288465b7bc52251e341.
