### ISSUE TITLE
Fix responsiveness of current style

### ISSUE THREAD

**Issue by locks** [EmberTown/ember-hearth#108]
There are some problems with the current CSS when you resize the window to smaller sizes.
Some help improving the situation would be helpful. I might update the issue with screenshots of specific situations to make it easier for contributors.

**Comment by jkarsrud** [comment]
An example of one of the problems with the current CSS on smaller windows; 
![image 2016-02-26 at 1 48 40 pm](https://cloud.githubusercontent.com/assets/185357/13699083/6d1f582e-e778-11e5-99f5-7ff8526c4d5e.png)
