### ISSUE TITLE
Test hearth install flow from the beginning

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#33]
Removing node and npm:
http://stackoverflow.com/a/11178106/3616239

Removing embercli, phantomjs and bower:
`npm uninstall -g bower`
`npm uninstall -g ember-cli`
`npm uninstall -g phantomjs`

**Comment by kimroen** [comment]
I think you need `-g` on those last three.

**Comment by thomassnielsen** [comment]
Indeed, updated. Thanks.
