### ISSUE TITLE
Decide policy for automatic updates

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#41]
The default behavior for Sparkle is to ask the user if they would like to automatically check for updates (on second launch, I think).

We can do one of these:
1. Ask the user like now, and have a setting for changing their mind
2. Have it on by default and have a setting to turn it off (don't ask the user)
3. Always have it on and provide no setting (don't ask the user)

I think number 1 is the best option, but would like more opinions.

**Comment by thomassnielsen** [comment]
Also for 1.
Checkbox in settings should do the trick.

**Comment by kimroen** [comment]
Decided! Issue for implemting: #54.
