### ISSUE TITLE
[Discussion] Cross platform support

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#47]
Sparked by https://twitter.com/ebryn/status/587377900170518528
Can we make Ember Hearth cross platform with Windows and other *NIXes?
E.g. by writing it in NW.js or Atom Shell.

**Comment by thomassnielsen** [comment]
Personally I feel like the app should at least have a native feel, and make use of such features as running in the menu bar, etc. We could still write the application logic and most of the UI cross platform, and wrap it with webkit.

I'm not familiar with the Ember stack on other platforms, especially Windows (I expect it to be pretty similar on *nix). Is it similar enough that it's worth attempting?

Also, best practices vary from platform to platform. On *nix I suspect you want to install mostly everything through a package manager, while on Windows that's not a thing. If this is the case, would we end up with so many if/elses that it may as well be separate projects, or will it still be worth consolidating what we can?

**Comment by locks** [comment]
On it! ;)
