### ISSUE TITLE
[Feature] Generate blueprints

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#66]
This is a pretty big one, with many steps. Checkboxes for broad strokes:
- [ ] Figure out how the UI should work
- [ ] Figure out a way to list available blueprints (addons may add more)
- [ ] Implement MVP (pick blueprint, textfield for arguments)
- [ ] Implement full UI

**Comment by stefanpenner** [comment]
> Figure out a way to list available blueprints (addons may add more)

we should add `ember help --json` to ember-cli so tooling can consume. This help printing internals should actually just start using the JSON format, and passing it off to a humanized printer to emit the current stuff, and the raw for `--json`

**Comment by thomassnielsen** [comment]
@stefanpenner do you think it is possible to implement this with an addon first, or should one look directly at implementing it in ember-cli? Trying to assess the scope of this.
