### ISSUE TITLE
Find, install and manage addons

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#71]
You should be able to list installed addons, remove and update them, and install new ones.

**Comment by kimroen** [comment]
For the installing-part, emberaddons.com and emberobserver.com each have their own endpoint for listing these. They are:

Emberaddons: https://io-builtwithember-addons-data.s3.amazonaws.com/addons.json
Ember Observer: http://emberobserver.com/api/addons

We could use one of these, or have our own.

**Comment by thomassnielsen** [comment]
Any gut feeling for which one we should use?

**Comment by kimroen** [comment]
There's some talk that the two services might merge, but I'm not sure which API they'll go with.

The one from EmberAddons is more straight-forward, but the one from Ember Observer has some more site-specific data (that we might want to show in the listing).

We don't have to decide right now, but it'll depend on external events and what kind of design we end up going for.
