### ISSUE TITLE
The title bar of projects looks draggable

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#78]
We fixed the fact that you could drag to resize in #77, but if you hover over the line the cursor still changes to a drag-handle.

**Comment by thomassnielsen** [comment]
We can hide the drag-bar completely (and create a non-draggable replacement if we want the line there). Does that sound like a good solution to you? And if so, should we make a replacement bar?

**Comment by thomassnielsen** [comment]
Never mind, `- splitView:shouldHideDividerAtIndex:` isn't actually for hiding the divider, but is used to determine the behavior when it goes off screen. I should, however, be able to disable dragging completely using `- splitView:effectiveRect:forDrawnRect:ofDividerAtIndex:`.

**Comment by kimroen** [comment]
:clap: :clap: :clap:
