### ISSUE TITLE
Grab name for existing projects

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#8]
currently opening existing projects set them as unnamed.

**Comment by thomassnielsen** [comment]
@kimroen where to grab this from? package.json has it, but is there a more reliable place?

**Comment by kimroen** [comment]
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/bower.json#L2
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L2
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/app/index.html#L21
https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/environment.js#L5

One of these? Not sure where the canonical name used by ember-cli is. It's hardcoded several places.

**Comment by kimroen** [comment]
Looks like `name` in `package.json` is the canonical name :)

**Comment by thomassnielsen** [comment]
Thanks, will implement

**Comment by kimroen** [comment]
For future reference - the `Project` model in `ember-cli` has a `pkg` instance-variable which is an object representing the parsed `package.json`-file. [The `name` of the `Project` instance is an alias to `this.pkg.name`.](https://github.com/ember-cli/ember-cli/blob/0093f7a6d862b36106138f63d23bb96ed016bd6f/lib/models/project.js#L95)
