### ISSUE TITLE
"Ember server started" stays on screen

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#80]
The notification telling you that the server has started will stay on screen until the user has taken an action. It shouldn't do that.

**Comment by kimroen** [comment]
http://stackoverflow.com/questions/12320051/can-an-app-use-both-alerts-and-banners-in-notification-center

Looks like when you set `NSUserNotificationAlertStyle` (in `Info.plist`) to something, that is the style for all notifications from the app, unless the user overrides it. The `alert` type has the behavior described in the issue description - no getting around it.

If we want buttons, this is the style we need to use.

There's some private functionality which is what iTunes uses for instance, but that is, well, private.
http://stackoverflow.com/a/23087567/1901084

**Comment by thomassnielsen** [comment]
As long as it's easy to change this in settings, I suggest we keep it as is.

**Comment by thomassnielsen** [comment]
Since we fixed #82, and users can change this in notification settings, I'm considering this fixed.
