### ISSUE TITLE
Notifications stack up

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#82]
The notifications that say the server has started stacks up in the notification center. When you click them, the browser opens with `localhost`.

If we can clear them manually, we should do so when the server it is notifying about is turned off.

**Comment by thomassnielsen** [comment]
`UserNotificationCenter.defaultUserNotificationCenter().removeAllDeliveredNotifications()` should do the trick. At what point should we do this? (There is also a way to clear a specific notification if you keep a reference to it, but I don't think we need to be that granular).

**Comment by kimroen** [comment]
Every time the server quits without an error, maybe?

**Comment by thomassnielsen** [comment]
As well as on app launch and termination, I guess?

**Comment by kimroen** [comment]
Yeah, that sounds like a fair compromise.
