### ISSUE TITLE
Says folder already exists when it doesn't.

### ISSUE THREAD

**Issue by Samsinite** [EmberTown/ember-hearth#84]
Was unable to create a project. Regardless of the name, it always said there was a folder name conflict.

**Comment by thomassnielsen** [comment]
Sorry about that, must be an overzealous feature. I'll have i fix up soon.

**Comment by Samsinite** [comment]
Np, was actually surprised someone hadn't already reported it. Nice work on the project, it is good to see that there is starting to be an easier way to help people unfamiliar with the node eco-system and command line get up and running.

**Comment by thomassnielsen** [comment]
Thanks, and thanks for the bug report. This early we're pushing often and early, but it's no fun when new users experience these problems. I'll be pushing out a 0.3.1 shortly to rectify the issue for new and existing users.

**Comment by thomassnielsen** [comment]
[0.3.1](https://github.com/EmberTown/ember-hearth/releases/tag/0.3.1) is now out, fixing this and more.
