### ISSUE TITLE
Decide on an initial UI for addon discovery and management

### ISSUE THREAD

**Issue by kimroen** [EmberTown/ember-hearth#85]
This is a task to help accomplish #71 

Some interfaces from other people solving this:
#### Codekit

(source: [video showing how it works](https://www.youtube.com/watch?v=iiMMWGInPrg))
![codekit 2 using bower - youtube](https://cloud.githubusercontent.com/assets/520420/7412086/7ea1a368-ef3f-11e4-9069-69f226ee9a44.png)

![codekit 2 using bower - youtube](https://cloud.githubusercontent.com/assets/520420/7412096/96b266c2-ef3f-11e4-9fec-488d7986645e.png)
#### Atom

![settings - atom](https://cloud.githubusercontent.com/assets/520420/7412108/abe16bec-ef3f-11e4-93c5-0abc5e5388dd.png)
#### Sketch toolbox

![sketch toolbox](https://cloud.githubusercontent.com/assets/520420/7412113/c2a66922-ef3f-11e4-976e-59c26389363e.png)

**Comment by thomassnielsen** [comment]
I like how dash does it, maybe with the addition of a link to the project. Compact and simple (pretty similar to Sketch toolbox as well)
![skjermbilde 2015-04-30 kl 14 07 11](https://cloud.githubusercontent.com/assets/626954/7412353/3eca31b2-ef42-11e4-9926-1fd759ce9fc7.png)

**Comment by kimroen** [comment]
That is interesting. It could be something like the screenshot you have there, with the items on the left being:
- Addons
  - EmberAddons.com
  - Ember Observer
- Bower

Not sure how that translates to managing installed addons though. I have a feeling installing needs to be separate from managing, but I'd like them to be combined.

**Comment by thomassnielsen** [comment]
I think it would work fine to have them combined as long as you have an [ all | installed | not installed] filter toggle.

**Comment by kimroen** [comment]
I just think the info needed for each item might vary for the different uses.

**Comment by thomassnielsen** [comment]
Care to elaborate? I'm not sure what kind of info that would be.
