### ISSUE TITLE
Refactor tools to init with path, not take path as argument

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#92]
Currently all tools take path as an argument when running commands. Most of them, and especially EmberCLI, should have path as a property (also settable with a convenience init), and should not require the path to be passed for every task run.

Currently:

``` swift
let ember = EmberCLI()
ember.test(project.path!, type: .browser)
```

A better future:

``` swift
let ember = EmberCLI(path: project.path!)
ember.test(.browser)
```

This should also work:

``` swift
let ember = EmberCLI()
ember.path = project.path!
ember.test(.browser)
```

**Comment by thomassnielsen** [comment]
Consider renaming `path` to `workingPath` or `directoryPath` for clarity. This mirrors what NSTask uses under the hood.

**Comment by kimroen** [comment]
How about passing in (or otherwise linking) the project object and the tool?

**Comment by thomassnielsen** [comment]
Interesting option. I think it's worth considering if we ever need something else than the path, and again especially for EmberCLI this might be useful. For the other tools I think we don't need to, and then it's better with the looser coupling that only passing the path gives.
