### ISSUE TITLE
Allow override of default browser/editor in settings

### ISSUE THREAD

**Issue by thomassnielsen** [EmberTown/ember-hearth#93]
Somebody (like myself) like to use a separate browser for testing than regular browsing (e.g. Safari vs. Chrome or Chrome Canary for testing). Right now we use the default browser, but we should allow changing this. 

The same goes for editor. We should hit most since we pick the default browser for js, but some Ember projects are written in Coffescript or Typescript, and some users might prefer a different editor for that.

**Comment by kimroen** [comment]
Would this be on a global or per-project basis? Or both? (global, with project-override?)

**Comment by thomassnielsen** [comment]
Global first and foremost, but per-project would be nice too.

**Comment by thomassnielsen** [comment]
Global implemented e1f7f6d4975879801529f21c0cb54df1c070df19

**Comment by thomassnielsen** [comment]
Closing this for now as we don't really have a system for per-project settings yet, and when we do it should be easy enough to implement this as one of the options.
