### ISSUE TITLE
[coming soon] ember help --json

### ISSUE THREAD

**Issue by stefanpenner** [EmberTown/ember-hearth#97]
FYI this may be of interest: https://github.com/ember-cli/ember-cli/pull/4576

**Comment by kimroen** [comment]
Squee!

**Comment by stefanpenner** [comment]
;)

**Comment by locks** [comment]
It hath landed!

**Comment by Turbo87** [comment]
is this actually used anywhere?

**Comment by locks** [comment]
Yup, https://github.com/EmberTown/ember-hearth/blob/electron/Architecture.md#example-commands

**Comment by Turbo87** [comment]
ah, looked at the wrong branch apparently :wink: 

but you are only using `ember help --json` not the special cases like `ember help generate model --json` for example, correct?

**Comment by locks** [comment]
@Turbo87 as far as I know that's correct, `ember help --json` already provides all the available help documentation.

**Comment by Turbo87** [comment]
> `ember help --json` already provides all the available help documentation

I agree on that. I was wondering if anyone actually used something like `ember help generate --json`, because it makes the code in `ember-cli` quite a bit more complicated and I don't really see any reason for keeping it.

**Comment by locks** [comment]
Oh, I agree. If I had enough time I'd help improve the programmatic API instead.

[edit] Well, I guess that wouldn't help command-line usage of `ember-cli`, but I meant separating the JSON outputting. At the moment we're shelling it out and parsing the output, which seems unnecessary.

**Comment by Turbo87** [comment]
@locks I've opened https://github.com/ember-cli/ember-cli/pull/5615, extracting the JSON generation code. We might be able to cache the output in a file and regenerate that file whenever addons are installed. 

see also https://github.com/ember-cli/ember-cli/pull/4709 for the origin of that idea
